import Head from 'next/head'
import 'material-icons/iconfont/material-icons.css';
import Image from 'next/image'
import HeroSection from '@/components/HeroSection';
import QuickLinks from '@/components/QuickLinks';
import MainHeader from '@/components/MainHeader';
 

export default function Home() {
  return (
    <>
      <Head>
        <title>levelUP Games</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
       
    <MainHeader></MainHeader>

    <HeroSection></HeroSection>

    <QuickLinks></QuickLinks>
        <section>
       <div className='container pt-10 mx-20'>
        <h2>Shop Featured Games</h2>
       </div>
        </section>

      


      </main>
    </>
  )
}
